sonar.organization=inigoo96
sonar.projectKey=inigoo96_movies-api
sonar.projectName=movies-api

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
